config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  # redundante, :resources substitui essas 8 rotas || as = path
  get '/posts', controller: 'posts', action:'index', as: 'posts'
  post '/posts', controller: 'posts', action: 'create'
  get '/posts/new', controller: 'posts', action: 'new', as: 'new_post'
  get '/posts/:id/edit', controller: 'posts', action: 'edit', as: 'edit_post'
  get '/posts/:id', controller: 'posts', action: 'show', as: 'post'
  patch '/posts/:id', controller: 'posts', action: 'update'
  put '/posts/:id', controller: 'posts', action: 'update'
  delete '/posts/:id', controller: 'posts', action: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	# validando campos
	validates :title, :description, :body, :author, :presence => true
	validates :title, :description, :author, :length => {:maximum => 60 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	layout 'posts'
	before_action :find_post, except: [:index, :create, :new]

	def index
		@posts = Post.all.order("created_at ASC")
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to posts_path, notice: t("success!")
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to posts_path, notice: t("updated!")
		else
			render :edit
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path, alert: t("deleted!")
	end

	private
	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :description, :body, :author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="PT-BR">
  <head>
    <title><%= t('test1') %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html lang="PT-BR">
  <head>
    <title><%= t('test1') %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'posts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'posts', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "layouts/shared/header", cached: true %>
  <main class="container">
    <section class="row">
      <%= yield %>
    </section>
  </main>
    
  <%= render partial: "layouts/shared_notice/notifications", cached: true %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse" style="opacity: 0.9; border-radius:0;">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only"><%= t 'toggle' %></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
			</button>
			<li>
					<%= link_to "Blog Rails", posts_path, class:"navbar-brand" %>
			</li>
		</div>
	
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li>
						<%= link_to t("create"), new_post_path, role: "button" %>
				</li>
				<li>
						<%= link_to t("list"), posts_path, role: "button" %>
				</li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/shared_notice/_notifications.html.erb
<% if notice %>
<%= javascript_tag "$.notify({ message: '#{notice}'}, {type: 'success', placement: {from: 'top', align: 'center'}});" %>
<% end %>

<% if alert %>
<%= javascript_tag "$.notify({ message: '#{alert}'}, {type: 'info', placement: {from: 'top', align: 'center'}});" %>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: "posts/shared/form", cached: true %>

app/views/posts/index.html.erb
<div class="col-lg-8">
	<div class="panel panel-primary">
		<div class="panel-body">
			<span><%= t('ola') %> <%= link_to t("create"), new_post_path, id: "Criar" %></span>
		</div>
	</div>
	<% @posts.each do |post| %>
		<% cache post do %>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h1 class="panel-title"><%= t 'article' %> <%= post.id %></h1>
		</div>
		<div class="panel-body">
			<h1><%= link_to post.title, post_path(post) %></h1>

			<p class="lead">
				<%= t 'by' %> <%= link_to post.author, post_path(post) %>
			</p>
			<hr>
			<p><span class="glyphicon glyphicon-time"></span> <%= t 'created_at' %> <strong><%= time_ago_in_words(post.created_at) %></strong> <%= t ('at') %> <strong><%= l (post.created_at) %></strong></p>
			<p><span class="glyphicon glyphicon-time"></span> <%= t 'updated_at' %> <strong><%= time_ago_in_words(post.updated_at) %></strong> <%= t ('at') %> <strong><%= l (post.updated_at) %></strong></p>
			<hr>

			<blockquote>
			<p><%= truncate(post.body, length: 100) %></p>
			</blockquote>
			<hr>
			<%= link_to t("view"), post_path(post), class: "btn btn-info pull-right" %>
		</div>
	</div>
		<% end %>
	<% end %>
</div>
<aside class="col-md-4">
	<section class="list-group">
		<a href="#" class="list-group-item active">
		<%= t 'orderByTitle' %>
		</a>
		<% @posts.each do |post| %>
			<% cache post do %>
				<%= link_to post.title, post_path(post), class: "list-group-item" %>
			<% end %>
		<% end %>
	</section>
</aside>

app/views/posts/new.html.erb
<%= render partial: "posts/shared/form", cached: true %>

app/views/posts/shared/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading"><%= t 'article' %></div>
	<div class="panel-body">
		<% if @post.errors.any? %>
			<% @post.errors.full_messages.each do |message| %>
				<% cache message do %>
		<div type="button" class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
			<li><%= message %></li>
		</div>
				<% end %>
			<% end %>
		<% end %>

		<%= form_for @post, :html => { id: "form" } do |f| %>
			<div class="col-md-6">
				<div class="form-group has-success has-feedback">
					<%= f.label :title, 'Título' %>
					<%= f.text_field :title, class: "form-control", placeholder: "Título", :maxlength => "60" %>
				</div>
			</div>

			<div class="col-md-6">
				<div class="form-group has-success has-feedback">
					<%= f.label :description, 'Assunto' %>
					<%= f.text_field :description, class: "form-control", placeholder: "Tema do artigo", :maxlength => "60" %>
				</div>    
			</div>

			<div class="col-md-12">
				<div class="form-group has-success has-feedback">
					<%= f.label :author, 'Autor' %>
					<%= f.text_field :author, class: "form-control", placeholder: "Quem está escrevendo?", :maxlength => "60" %>
				</div>    
			</div>

			<div class="col-md-12">
				<div class="form-group has-success has-feedback">
					<%= f.label :body, 'Artigo' %>
					<%= f.text_area :body, class: "form-control area", placeholder: "Disserte aqui", rows: 15, data: { provide: 'markdown' } %>
				</div>    
			</div>

			<div class="col-md-1 form-group">
				<%= submit_tag t("submit"), class: "btn btn-success" %>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h4><%= t 'preview' %> <span><%= @post.id %></span></h4>
  </div>
  <div class="panel-body">
    <h1><%= @post.title %></h1>
    <p class="lead"><%= t 'by' %> <span class="author"><%=  @post.author %></span></p>
    <hr>
    <p><span class="glyphicon glyphicon-time"></span> <%= t 'created_at' %> <strong><%= time_ago_in_words(@post.created_at) %></strong> <%= t ('at') %> <strong><%= l (@post.created_at) %></strong></p>
    <p><span class="glyphicon glyphicon-time"></span> <%= t 'updated_at' %> <strong><%= time_ago_in_words(@post.updated_at) %></strong> <%= t ('at') %> <strong><%= l (@post.updated_at) %></strong></p>
    <hr>
    <div class="well">
      <blockquote>
        <%= @post.description %>
      </blockquote>
      <hr>
      <p><%= @post.body %></p>
    </div>    
    <hr>
    <div class="btn-group pull-right" role="group">
      <%= link_to "Listar artigos", posts_path, class: "btn btn-success" %>
      <%= link_to "Editar", edit_post_path(@post), class: "btn btn-default" %>
      <%= link_to "Criar novo artigo", new_post_path, class: "btn btn-info" %>
      <%= link_to "Deletar", post_path(@post), class: "btn btn-danger", method: :delete, data: { confirm: t('sure?') } %>
    </div>
  </div>
</div>